# Generated by Django 4.2.16 on 2024-09-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=260)),
                ('completed', models.BooleanField(default=False)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
